apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"web-svc","namespace":"app-demo"},"spec":{"ports":[{"nodePort":30080,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"web-app"},"type":"NodePort"}}
  creationTimestamp: "2025-09-24T15:01:30Z"
  name: web-svc
  namespace: app-demo
  resourceVersion: "2402849"
  uid: 76168511-0e43-4759-97f8-bded31e64c0c
spec:
  clusterIP: 10.152.183.85
  clusterIPs:
  - 10.152.183.85
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
