apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
          readOnly: true
      - name: multitool
        image: wbitt/network-multitool
        command: ["sleep","infinity"]
      volumes:
      - name: web-content
        configMap:
          name: web-content
