apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: app-demo
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80        # порт сервиса внутри кластера
    targetPort: 80  # на какой порт контейнера nginx отправлять
    name: http
  type: ClusterIP   # можно заменить на NodePort для доступа снаружи
