apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: app-demo
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
